language: node_js
node_js:
- '4'
- '5'
- '6'
env:
  matrix:
  - CXX=g++-4.8
  global:
    secure: HcqYjdRCRD+io3gcLTSnPbQUbOPRk6FwWzea+Di7v/GT8zB5CdkjDaMUUdWOmYsSGI2SDUM++F4u8XL1JjAE2/AVVkPdAzf1n+fTGfZrnawrPozeyB/OdkHu+Sh6MDgkn4mUqLhee17DL0AQpV9CbXiXUHzN7NpRPzRHrbjG6Ly6vCrNjc1czrwRRd5PMUdCvGwbOjwZltqnLPs3uI8qJU22IdnQ2blovj/f7D2WJdCRWjv6989sFBnwXX4F6bxT6PNIhZXZL0i+yy0YSvB1FI5VqQdYn1Uqe3uinvB7vuUOi2tN5W1ihljlCmNa64l3wJLOQbRjW9e+1RCOtRnSBlBbNnnhs6oZN8Bx/MFTXBnpoNAvLsYRsXhlcb0ckyOmIC7aynJwCl7tnzaJLau1L0wWJPkc7vUNcezadyMNtRppTAk6gwSkh6REc+D4//A778ZbfHTuD5/mcjsFnDCIXqpAxBbqYE84b3FmZD4sLgPUyVF/jQIBPG+gaK+BI4antwzdLPIa+N4gjlztQ0NKU+jA1yLhptCNLQg7FGTKFo9CVR5ZqK/HdWfm91FXu+wDtNtcwM2STwr5Sr1GfRIYAAlLNTEKf5/euRkZi+Anbhikc5MzH0NHeslXTPOaLbk+Cnd6lekSVVQtc5Pr1e4sIYUF4NeC6mNGEfX1+wmkdaw=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - lib32stdc++6
    - lib32z1
before_install:
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- npm install -g npm@latest
install:
- npm install -g bower cordova ionic aws-cli
- npm install
- bower update
before_script:
- wget http://dl.google.com/android/android-sdk_r24.4-linux.tgz
- tar -xvf android-sdk_r24.4-linux.tgz
- echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter platform-tools
- echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter build-tools-23.0.2
- echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter android-23
- echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-support
- echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-m2repository
- echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-google-m2repository
- export ANDROID_HOME=$PWD/android-sdk-linux
- export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/23.0.2
script:
- ionic platform remove android
- ionic platform add android
- ionic build android
- mv /home/travis/build/shirkeyaws/myapp/platforms/android/build/outputs/apk/android-debug.apk ./test.apk
- aws --region us-west-2 devicefarm create-upload --name test.apk --type ANDROID_APP --project-arn arn:aws:devicefarm:us-west-2:306280812807:project:a7645c59-b12a-488a-b422-0ea0ead489e1
